apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ndm.nodeDiskOperator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .Values.nodeDiskOperator.name  }}
  template:
    metadata:
      labels:
        name: {{ .Values.nodeDiskOperator.name  }}
    spec:
      serviceAccountName: {{ include "ndm.serviceAccountName" . }}
      containers:
        - name: {{ .Values.nodeDiskOperator.name  }}
          image: "{{ .Values.nodeDiskOperator.image.registry }}{{ .Values.nodeDiskOperator.image.repository }}:{{ .Values.nodeDiskOperator.image.tag }}"
          ports:
            - containerPort: 8080
              name: liveness
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # the service account of this pod
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: OPERATOR_NAME
              value: {{ .Values.nodeDiskOperator.name  }}
            - name: CLEANUP_JOB_IMAGE
              value: "{{ .Values.cleanupUtil.image.registry }}{{ .Values.cleanupUtil.image.repository }}:{{ .Values.cleanupUtil.image.tag }}"
