apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ndm.clusterExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .Values.clusterExporter.name  }}
  template:
    metadata:
      labels:
        name: {{ .Values.clusterExporter.name  }}
    spec:
      serviceAccountName: {{ include "ndm.serviceAccountName" . }}
      containers:
        - name: {{ .Values.clusterExporter.name  }}
          image: "{{ .Values.clusterExporter.image.registry }}{{ .Values.clusterExporter.image.repository }}:{{ .Values.clusterExporter.image.tag }}"
          command:
            - /usr/local/bin/exporter
          args:
            - "start"
            - "--mode=cluster"
            - "--port=:9100"
            - "--metrics=/metrics"
          ports:
            - containerPort: 9100
              protocol: TCP
              name: metrics
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace