apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ndm.nodeExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: {{ .Values.nodeExporter.name  }}
  template:
    metadata:
      labels:
        name: {{ .Values.nodeExporter.name  }}
    spec:
      serviceAccountName: {{ include "ndm.serviceAccountName" . }}
      containers:
        - name: {{ .Values.nodeExporter.name  }}
          image: "{{ .Values.nodeExporter.image.registry }}{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          command:
            - /usr/local/bin/exporter
          args:
            - "start"
            - "--mode=node"
            - "--port=:9101"
            - "--metrics=/metrics"
          ports:
            - containerPort: 9101
              protocol: TCP
              name: metrics
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace